# Array Func

In [2]:
import numpy as np
arr=[]
s=int(input("What number of speed you want to enter?"))
for i in range(s):
  arr.append(float(input("Enter the speeds in km/hr:")))
arr=np.array(arr)
mean=sum(arr)//len(arr)
print("The Average Speed is:",mean,9"Km/hr")

What number of speed you want to enter?5
Enter the speeds in km/hr:45
Enter the speeds in km/hr:85
Enter the speeds in km/hr:90
Enter the speeds in km/hr:70
Enter the speeds in km/hr:60
The Average Speed is: 70.0 Km/hr


# Inexing/Slicing

In [3]:
import numpy as np
n=np.arange(20).reshape((5,4))
print("The Array is:",n)
print("The First two rows are:",n[[0,1],:])
print("The last two columns are:",n[[-2,-1]])


The Array is: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
The First two rows are: [[0 1 2 3]
 [4 5 6 7]]
The last two columns are: [[12 13 14 15]
 [16 17 18 19]]
