#4*5 Dimensional array using numpy

In [1]:
import numpy as np
s=np.arange(20)
print("Original Array:",)
print(s)
q=s.reshape((5,4))
print("Reshaped Array:")
print(q)
r=s.transpose()
print("Transpose of Array:")
print(r)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Transpose of Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Applying array Functions

In [10]:
import numpy as np
m=np.arange(1,5).reshape(2,2)
n=np.arange(6,10).reshape(2,2)
print("The First Array is:")
print(m)
print("The Second Array is:")
print(n)
print("Applying hstack() Func:")
array_1=np.hstack((m,n))
print(array_1)
print("Applying vstack() Func:")
array_2=np.vstack((m,n))
print(array_2)
print("Applying concatenate() Func:")
array_3=np.concatenate((m,n))
print(array_3)
print("Applying split() Func:")
array_4=np.array_split(array_1,2)
print(array_4)

The First Array is:
[[1 2]
 [3 4]]
The Second Array is:
[[6 7]
 [8 9]]
Applying hstack() Func:
[[1 2 6 7]
 [3 4 8 9]]
Applying vstack() Func:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying concatenate() Func:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying split() Func:
[array([[1, 2, 6, 7]]), array([[3, 4, 8, 9]])]
